"""add check.public_id

Revision ID: 381207562621
Revises: 91125b5423fd
Create Date: 2024-05-15 13:42:54.595989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "381207562621"
down_revision: Union[str, None] = "91125b5423fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checks",
        sa.Column(
            "public_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix__checks__public_id"), "checks", ["public_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__checks__public_id"), table_name="checks")
    op.drop_column("checks", "public_id")
    # ### end Alembic commands ###
