"""add check constraints

Revision ID: 2de9a4509b8e
Revises: 381207562621
Create Date: 2024-05-19 07:14:13.784884

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2de9a4509b8e"
down_revision: Union[str, None] = "381207562621"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "positive payment_amount", "checks", "payment_amount > 0"
    )
    op.create_check_constraint(
        "positive total", "checks", "total > 0"
    )
    op.create_check_constraint(
        "positive price", "products", "price > 0"
    )
    op.create_check_constraint(
        "positive quantity", "products", "quantity > 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "positive payment_amount", "checks", type_="check"
    )
    op.drop_constraint(
        "positive total", "checks", type_="check"
    )
    op.drop_constraint(
        "positive price", "products", type_="check"
    )
    op.drop_constraint(
        "positive quantity", "products", type_="check"
    )
    # ### end Alembic commands ###
